const $=id=>document.getElementById(id);let currentFile=null;
function trackAnonymousPrintVisit(){try{let id=localStorage.getItem("fusaa-anonymous-visitor");if(!id){id=globalThis.crypto?.randomUUID?.().replaceAll("-","")||("v"+Date.now()+Math.random().toString(36).slice(2));localStorage.setItem("fusaa-anonymous-visitor",id)}fetch("/api/v1/public/visits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitor_id:id,page:location.pathname.startsWith("/suivi/")?"tracking":"print"})}).catch(()=>{})}catch{}}
trackAnonymousPrintVisit();
function show(id){document.querySelectorAll(".screen").forEach(item=>item.classList.toggle("active",item.id===id));const step={stepFile:0,stepOptions:1,stepContact:2,stepDone:3}[id]??0;document.querySelectorAll(".stepper span").forEach((item,index)=>item.classList.toggle("active",index<=step))}
function formatMoney(value){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" F CFA"}
async function request(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw Error(data.detail||"La demande n’a pas pu être traitée.");return data}
$("guestFile")?.addEventListener("change",event=>{currentFile=event.target.files[0]||null;$("guestFileName").textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(2)} Mo`:"";$("toOptions").disabled=!currentFile});
$("toOptions")?.addEventListener("click",()=>show("stepOptions"));$("toContact")?.addEventListener("click",()=>show("stepContact"));document.querySelectorAll(".back").forEach(button=>button.addEventListener("click",()=>show(button.dataset.back)));
$("sendGuestOrder")?.addEventListener("click",async()=>{const phone=$("guestPhone").value.trim(),button=$("sendGuestOrder");if(!currentFile){alert("Choisissez un fichier.");return}if(phone.length<5){$("guestPhone").focus();return}button.disabled=true;button.textContent="Envoi en cours…";try{const body=new FormData();body.append("file",currentFile);body.append("phone",phone);body.append("display_name",$("guestName").value.trim());body.append("copies",$("guestCopies").value);body.append("paper_size",$("guestPaper").value);body.append("color_mode",document.querySelector('input[name="color"]:checked').value);body.append("duplex",$("guestDuplex").checked);const order=await request("/api/v1/public/orders",{method:"POST",body});$("guestPrice").textContent=formatMoney(order.estimated_cost);$("orderNumber").textContent=order.order_number;$("orderStatus").textContent=`Statut : ${order.status} · Paiement : ${order.payment_status} · Estimation : ${formatMoney(order.estimated_cost)}`;const url=new URL(order.tracking_url,location.origin).href;$("trackingLink").textContent=url;$("copyTracking").onclick=()=>navigator.clipboard?.writeText(url);show("stepDone")}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent="Envoyer ma commande"}});
let trackingPath=null,lastTrackingSignature=null,trackingTimer=null;
function paymentText(status){return {PAID:"confirmé",PENDING:"à confirmer",REJECTED:"à revoir"}[status]||status}
function updateTracking(order,notify){const signature=[order.status,order.payment_status,order.progress,order.updated_at].join("|");const changed=lastTrackingSignature&&lastTrackingSignature!==signature;lastTrackingSignature=signature;$("trackingResult").replaceChildren();const tag=document.createElement("span");tag.className="eyebrow";tag.textContent=order.stage;const title=document.createElement("h2");title.textContent=order.order_number;const file=document.createElement("p");file.textContent=order.document_name;const price=document.createElement("p");price.textContent=`Prix estimé : ${formatMoney(order.estimated_cost)} · Paiement ${paymentText(order.payment_status)}`;$("trackingResult").append(tag,title,file,price);$("trackingBar").style.width=`${order.progress}%`;$("trackingDetail").textContent=order.detail;$("trackingStamp").textContent=`Dernière mise à jour : ${new Date(order.updated_at).toLocaleString("fr-FR")}`;const step=order.progress>=100?5:order.progress>=85?4:order.progress>=55?3:order.progress>=30?2:1;document.querySelectorAll(".tracking-steps span").forEach((item,index)=>item.classList.toggle("done",index<step));if(changed&&notify&&Notification.permission==="granted")new Notification("FUSAA · suivi de commande",{body:`${order.order_number} : ${order.stage}`})}
async function refreshTracking(notify=false){if(!trackingPath)return;try{const order=await request(trackingPath);updateTracking(order,notify)}catch(error){$("trackingResult").textContent=error.message}}
async function loadTracking(){const match=location.pathname.match(/^\/suivi\/([^/]+)\/([^/]+)$/);if(!match)return;$("orderApp").classList.add("hidden");$("trackingApp").classList.remove("hidden");trackingPath=`/api/v1/public/orders/${encodeURIComponent(match[1])}/${encodeURIComponent(match[2])}`;$("trackingAlert").addEventListener("click",async()=>{if(!("Notification" in window)){alert("Les alertes ne sont pas disponibles dans ce navigateur.");return}const permission=await Notification.requestPermission();$("trackingAlert").textContent=permission==="granted"?"Alertes de suivi activées":"Alertes non autorisées"});await refreshTracking(false);trackingTimer=setInterval(()=>refreshTracking(true),15000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshTracking(true)})}
loadTracking();
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
const guestAiPrompts=["Quels formats sont acceptés ?","Comment obtenir le prix ?","Comment payer ?","Suivre ma commande"];
function renderGuestAiChips(items=guestAiPrompts){const target=$("guestAiChips");if(!target)return;target.replaceChildren(...items.map(item=>{const button=document.createElement("button");button.type="button";button.textContent=item;button.addEventListener("click",()=>askGuestAssistant(item));return button}))}
async function askGuestAssistant(prompt=null){const input=$("guestAiQuestion"),answer=$("guestAiAnswer"),button=$("guestAiAsk"),message=(prompt||input?.value||"").trim();if(!message){input?.focus();return}if(input)input.value=message;button.disabled=true;button.textContent="Réponse…";answer.textContent="Analyse de votre demande…";try{const data=await request("/api/v1/public/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,profile:trackingPath?"tracking_guest":"new_guest"})});$("guestAiTitle").textContent=data.title;answer.textContent=data.answer;renderGuestAiChips(data.suggestions||guestAiPrompts)}catch(error){answer.textContent=error.message}finally{button.disabled=false;button.textContent="Demander"}}
$("guestAiOpen")?.addEventListener("click",()=>{const dialog=$("guestAiDialog");if(!dialog.open)dialog.showModal();renderGuestAiChips()});$("guestAiAsk")?.addEventListener("click",()=>askGuestAssistant());$("guestAiQuestion")?.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();askGuestAssistant()}});
const PUBLIC_PAYMENT_TEXT="Paiement via MYNITA, AMANATA ou WAVE au +227 98313369. Pour discuter avec FUSAA sur WhatsApp : +227 90531465.";
document.querySelector("#stepContact .notice")?.insertAdjacentHTML("afterend",'<p class="notice" style="border-left-color:#32dfc4">'+PUBLIC_PAYMENT_TEXT+'</p>');
document.querySelector("#stepDone .success")?.insertAdjacentHTML("beforeend",'<p class="notice" style="border-left-color:#32dfc4">'+PUBLIC_PAYMENT_TEXT+'</p>');
document.head.insertAdjacentHTML("beforeend",'<style>.public-theme{width:auto;margin:0 10px 0 0;padding:8px 11px;border-radius:10px;background:#ffffff10;border:1px solid #ffffff20}:root[data-theme="light"]{color-scheme:light;background:#edf4f8;color:#14293d}:root[data-theme="light"] body{background:radial-gradient(circle at 90% -10%,#b9ebe466,transparent 30rem),#edf4f8;color:#14293d}:root[data-theme="light"] .top{border-color:#d5e3eb}:root[data-theme="light"] .brand{color:#14293d}:root[data-theme="light"] .top a{color:#216c70}:root[data-theme="light"] .card{background:linear-gradient(145deg,#ffffff,#f2f8fa);border-color:#cfdee7;box-shadow:0 24px 70px #52708920}:root[data-theme="light"] .hero p,:root[data-theme="light"] .muted,:root[data-theme="light"] .tracking-stamp{color:#536f83}:root[data-theme="light"] input,:root[data-theme="light"] select{background:#fff;color:#14293d;border-color:#a9c3d2}:root[data-theme="light"] .price,:root[data-theme="light"] .code{background:#edf6f8;color:#25465a}:root[data-theme="light"] .notice{color:#36586b;background:#fff4d9}:root[data-theme="light"] .tracking-steps span{color:#58758a;background:#dce9ee}:root[data-theme="light"] .secondary,:root[data-theme="light"] .public-theme{color:#25465a;background:#e7f0f4;border-color:#c7d9e3}:root[data-theme="light"] .guest-ai{color:#14293d;background:linear-gradient(145deg,#ffffff,#eaf6f7)}:root[data-theme="light"] .guest-ai-answer{color:#25465a;background:#edf8f7;border-color:#b9e6dd}:root[data-theme="light"] .guest-ai-close,:root[data-theme="light"] .guest-ai-chips button{color:#25465a;background:#e7f0f4}</style>');
function applyPublicTheme(mode){const theme=mode==="light"?"light":"dark";document.documentElement.dataset.theme=theme;localStorage.setItem("fusaa-theme",theme);const button=$("publicTheme");if(button)button.textContent=theme==="light"?"☾ Sombre":"☀ Clair";document.querySelector('meta[name="theme-color"]')?.setAttribute("content",theme==="light"?"#edf4f8":"#07111f")}
function togglePublicTheme(){applyPublicTheme(document.documentElement.dataset.theme==="light"?"dark":"light")}
const adminLink=document.querySelector('.top a[href="/admin"]');if(adminLink){adminLink.textContent="Se connecter";adminLink.insertAdjacentHTML("beforebegin",'<button id="publicTheme" class="public-theme" type="button"></button>');$("publicTheme").onclick=togglePublicTheme}applyPublicTheme(localStorage.getItem("fusaa-theme")||"dark");window.addEventListener("storage",event=>{if(event.key==="fusaa-theme")applyPublicTheme(event.newValue||"dark")});
document.head.insertAdjacentHTML("beforeend",'<style>button:not(:disabled){transition:transform .2s ease,filter .2s ease,box-shadow .25s ease!important;transform-origin:center}button.fusaa-clicked:not(:disabled){animation:fusaaButtonClick .62s cubic-bezier(.2,.8,.25,1);filter:brightness(1.12);box-shadow:0 0 0 5px #35dfc236,0 0 26px #2d9bf066!important}@keyframes fusaaButtonClick{0%{transform:scale(1)}26%{transform:translateY(2px) scale(.94)}58%{transform:translateY(-1px) scale(1.025)}100%{transform:scale(1)}}@media(prefers-reduced-motion:reduce){button.fusaa-clicked:not(:disabled){animation:none}}</style>');
function animatePublicButton(button){if(!button||button.disabled)return;button.classList.remove("fusaa-clicked");void button.offsetWidth;button.classList.add("fusaa-clicked");setTimeout(()=>button.classList.remove("fusaa-clicked"),650)}document.addEventListener("click",event=>animatePublicButton(event.target.closest("button")),true);document.addEventListener("submit",event=>animatePublicButton(event.target.querySelector('button[type="submit"],button')),true);
let publicOperationDepth=0;function showPublicOperation(label="Traitement de votre demande…"){let panel=$("publicOperation");if(!panel){document.body.insertAdjacentHTML("beforeend",'<div id="publicOperation" class="public-operation" role="status" aria-live="polite"><div><i></i><b id="publicOperationLabel"></b><span>FUSAA prépare votre demande</span><em><u></u></em></div></div>');panel=$("publicOperation")}publicOperationDepth++;$("publicOperationLabel").textContent=label;panel.classList.add("active");return performance.now()}async function hidePublicOperation(start){const remaining=Math.max(0,700-(performance.now()-start));if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));publicOperationDepth=Math.max(0,publicOperationDepth-1);if(!publicOperationDepth)$("publicOperation")?.classList.remove("active")}
const publicRequestBase=request;request=async function(path,options={}){const animated=String(options.method||"GET").toUpperCase()!=="GET",started=animated?showPublicOperation(options.method==="POST"?"Envoi et enregistrement…":"Mise à jour en cours…"):0;try{return await publicRequestBase(path,options)}finally{if(animated)await hidePublicOperation(started)}};
document.head.insertAdjacentHTML("beforeend",'<style>.public-operation{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:20px;background:#03101a70;backdrop-filter:blur(6px);opacity:0;pointer-events:none;transition:opacity .2s ease}.public-operation.active{opacity:1;pointer-events:auto}.public-operation>div{width:min(360px,100%);padding:28px;border:1px solid #46e1ce88;border-radius:24px;background:linear-gradient(145deg,#123149f7,#071522fa);box-shadow:0 28px 90px #000a;text-align:center}.public-operation i{display:block;width:58px;height:58px;margin:0 auto 16px;border:5px solid #ffffff18;border-top-color:#36e1c7;border-right-color:#287cf0;border-radius:50%;animation:publicOperationSpin .8s linear infinite}.public-operation b{display:block;color:#effbff;font-size:1.05rem}.public-operation span{display:block;margin:7px 0 16px;color:#a7c3d3;font-size:.82rem}.public-operation em{display:block;height:7px;overflow:hidden;border-radius:99px;background:#ffffff14}.public-operation u{display:block;width:48%;height:100%;border-radius:inherit;background:linear-gradient(90deg,#25d3b8,#287cf0);animation:publicOperationLoad 1.05s ease-in-out infinite}@keyframes publicOperationSpin{to{transform:rotate(360deg)}}@keyframes publicOperationLoad{50%{transform:translateX(108%)}}:root[data-theme="light"] .public-operation>div{background:linear-gradient(145deg,#fff,#eaf6f7)}:root[data-theme="light"] .public-operation b{color:#183247}:root[data-theme="light"] .public-operation span{color:#557185}@media(prefers-reduced-motion:reduce){.public-operation i,.public-operation u{animation:none}}</style>');
