const $=id=>document.getElementById(id);let currentFile=null;
function show(id){document.querySelectorAll(".screen").forEach(item=>item.classList.toggle("active",item.id===id));const step={stepFile:0,stepOptions:1,stepContact:2,stepDone:3}[id]??0;document.querySelectorAll(".stepper span").forEach((item,index)=>item.classList.toggle("active",index<=step))}
function formatMoney(value){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" F CFA"}
async function request(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw Error(data.detail||"La demande n’a pas pu être traitée.");return data}
$("guestFile")?.addEventListener("change",event=>{currentFile=event.target.files[0]||null;$("guestFileName").textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(2)} Mo`:"";$("toOptions").disabled=!currentFile});
$("toOptions")?.addEventListener("click",()=>show("stepOptions"));$("toContact")?.addEventListener("click",()=>show("stepContact"));document.querySelectorAll(".back").forEach(button=>button.addEventListener("click",()=>show(button.dataset.back)));
$("sendGuestOrder")?.addEventListener("click",async()=>{const phone=$("guestPhone").value.trim(),button=$("sendGuestOrder");if(!currentFile){alert("Choisissez un fichier.");return}if(phone.length<5){$("guestPhone").focus();return}button.disabled=true;button.textContent="Envoi en cours…";try{const body=new FormData();body.append("file",currentFile);body.append("phone",phone);body.append("display_name",$("guestName").value.trim());body.append("copies",$("guestCopies").value);body.append("paper_size",$("guestPaper").value);body.append("color_mode",document.querySelector('input[name="color"]:checked').value);body.append("duplex",$("guestDuplex").checked);const order=await request("/api/v1/public/orders",{method:"POST",body});$("guestPrice").textContent=formatMoney(order.estimated_cost);$("orderNumber").textContent=order.order_number;$("orderStatus").textContent=`Statut : ${order.status} · Paiement : ${order.payment_status} · Estimation : ${formatMoney(order.estimated_cost)}`;const url=new URL(order.tracking_url,location.origin).href;$("trackingLink").textContent=url;$("copyTracking").onclick=()=>navigator.clipboard?.writeText(url);show("stepDone")}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent="Envoyer ma commande"}});
let trackingPath=null,lastTrackingSignature=null,trackingTimer=null;
function paymentText(status){return {PAID:"confirmé",PENDING:"à confirmer",REJECTED:"à revoir"}[status]||status}
function updateTracking(order,notify){const signature=[order.status,order.payment_status,order.progress,order.updated_at].join("|");const changed=lastTrackingSignature&&lastTrackingSignature!==signature;lastTrackingSignature=signature;$("trackingResult").replaceChildren();const tag=document.createElement("span");tag.className="eyebrow";tag.textContent=order.stage;const title=document.createElement("h2");title.textContent=order.order_number;const file=document.createElement("p");file.textContent=order.document_name;const price=document.createElement("p");price.textContent=`Prix estimé : ${formatMoney(order.estimated_cost)} · Paiement ${paymentText(order.payment_status)}`;$("trackingResult").append(tag,title,file,price);$("trackingBar").style.width=`${order.progress}%`;$("trackingDetail").textContent=order.detail;$("trackingStamp").textContent=`Dernière mise à jour : ${new Date(order.updated_at).toLocaleString("fr-FR")}`;const step=order.progress>=100?5:order.progress>=85?4:order.progress>=55?3:order.progress>=30?2:1;document.querySelectorAll(".tracking-steps span").forEach((item,index)=>item.classList.toggle("done",index<step));if(changed&&notify&&Notification.permission==="granted")new Notification("FUSAA · suivi de commande",{body:`${order.order_number} : ${order.stage}`})}
async function refreshTracking(notify=false){if(!trackingPath)return;try{const order=await request(trackingPath);updateTracking(order,notify)}catch(error){$("trackingResult").textContent=error.message}}
async function loadTracking(){const match=location.pathname.match(/^\/suivi\/([^/]+)\/([^/]+)$/);if(!match)return;$("orderApp").classList.add("hidden");$("trackingApp").classList.remove("hidden");trackingPath=`/api/v1/public/orders/${encodeURIComponent(match[1])}/${encodeURIComponent(match[2])}`;$("trackingAlert").addEventListener("click",async()=>{if(!("Notification" in window)){alert("Les alertes ne sont pas disponibles dans ce navigateur.");return}const permission=await Notification.requestPermission();$("trackingAlert").textContent=permission==="granted"?"Alertes de suivi activées":"Alertes non autorisées"});await refreshTracking(false);trackingTimer=setInterval(()=>refreshTracking(true),15000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshTracking(true)})}
loadTracking();
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
const guestAiPrompts=["Quels formats sont acceptés ?","Comment obtenir le prix ?","Comment payer ?","Suivre ma commande"];
function renderGuestAiChips(items=guestAiPrompts){const target=$("guestAiChips");if(!target)return;target.replaceChildren(...items.map(item=>{const button=document.createElement("button");button.type="button";button.textContent=item;button.addEventListener("click",()=>askGuestAssistant(item));return button}))}
async function askGuestAssistant(prompt=null){const input=$("guestAiQuestion"),answer=$("guestAiAnswer"),button=$("guestAiAsk"),message=(prompt||input?.value||"").trim();if(!message){input?.focus();return}if(input)input.value=message;button.disabled=true;button.textContent="Réponse…";answer.textContent="Analyse de votre demande…";try{const data=await request("/api/v1/public/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,profile:trackingPath?"tracking_guest":"new_guest"})});$("guestAiTitle").textContent=data.title;answer.textContent=data.answer;renderGuestAiChips(data.suggestions||guestAiPrompts)}catch(error){answer.textContent=error.message}finally{button.disabled=false;button.textContent="Demander"}}
$("guestAiOpen")?.addEventListener("click",()=>{const dialog=$("guestAiDialog");if(!dialog.open)dialog.showModal();renderGuestAiChips()});$("guestAiAsk")?.addEventListener("click",()=>askGuestAssistant());$("guestAiQuestion")?.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();askGuestAssistant()}});
const PUBLIC_PAYMENT_TEXT="Paiement via MYNITA, AMANATA ou WAVE au +227 98313369. Pour discuter avec FUSAA sur WhatsApp : +227 90531465.";
document.querySelector("#stepContact .notice")?.insertAdjacentHTML("afterend",'<p class="notice" style="border-left-color:#32dfc4">'+PUBLIC_PAYMENT_TEXT+'</p>');
document.querySelector("#stepDone .success")?.insertAdjacentHTML("beforeend",'<p class="notice" style="border-left-color:#32dfc4">'+PUBLIC_PAYMENT_TEXT+'</p>');
document.head.insertAdjacentHTML("beforeend",'<style>.public-theme{width:auto;margin:0 10px 0 0;padding:8px 11px;border-radius:10px;background:#ffffff10;border:1px solid #ffffff20}:root[data-theme="light"]{color-scheme:light;background:#edf4f8;color:#14293d}:root[data-theme="light"] body{background:radial-gradient(circle at 90% -10%,#b9ebe466,transparent 30rem),#edf4f8;color:#14293d}:root[data-theme="light"] .top{border-color:#d5e3eb}:root[data-theme="light"] .brand{color:#14293d}:root[data-theme="light"] .top a{color:#216c70}:root[data-theme="light"] .card{background:linear-gradient(145deg,#ffffff,#f2f8fa);border-color:#cfdee7;box-shadow:0 24px 70px #52708920}:root[data-theme="light"] .hero p,:root[data-theme="light"] .muted,:root[data-theme="light"] .tracking-stamp{color:#536f83}:root[data-theme="light"] input,:root[data-theme="light"] select{background:#fff;color:#14293d;border-color:#a9c3d2}:root[data-theme="light"] .price,:root[data-theme="light"] .code{background:#edf6f8;color:#25465a}:root[data-theme="light"] .notice{color:#36586b;background:#fff4d9}:root[data-theme="light"] .tracking-steps span{color:#58758a;background:#dce9ee}:root[data-theme="light"] .secondary,:root[data-theme="light"] .public-theme{color:#25465a;background:#e7f0f4;border-color:#c7d9e3}:root[data-theme="light"] .guest-ai{color:#14293d;background:linear-gradient(145deg,#ffffff,#eaf6f7)}:root[data-theme="light"] .guest-ai-answer{color:#25465a;background:#edf8f7;border-color:#b9e6dd}:root[data-theme="light"] .guest-ai-close,:root[data-theme="light"] .guest-ai-chips button{color:#25465a;background:#e7f0f4}</style>');
function applyPublicTheme(mode){const theme=mode==="light"?"light":"dark";document.documentElement.dataset.theme=theme;localStorage.setItem("fusaa-theme",theme);const button=$("publicTheme");if(button)button.textContent=theme==="light"?"☾ Sombre":"☀ Clair";document.querySelector('meta[name="theme-color"]')?.setAttribute("content",theme==="light"?"#edf4f8":"#07111f")}
function togglePublicTheme(){applyPublicTheme(document.documentElement.dataset.theme==="light"?"dark":"light")}
const adminLink=document.querySelector('.top a[href="/admin"]');if(adminLink){adminLink.textContent="Se connecter";adminLink.insertAdjacentHTML("beforebegin",'<button id="publicTheme" class="public-theme" type="button"></button>');$("publicTheme").onclick=togglePublicTheme}applyPublicTheme(localStorage.getItem("fusaa-theme")||"dark");window.addEventListener("storage",event=>{if(event.key==="fusaa-theme")applyPublicTheme(event.newValue||"dark")});
