const $=id=>document.getElementById(id);let currentFile=null;
function show(id){document.querySelectorAll(".screen").forEach(item=>item.classList.toggle("active",item.id===id));const step={stepFile:0,stepOptions:1,stepContact:2,stepDone:3}[id]??0;document.querySelectorAll(".stepper span").forEach((item,index)=>item.classList.toggle("active",index<=step))}
function formatMoney(value){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" F CFA"}
async function request(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw Error(data.detail||"La demande n’a pas pu être traitée.");return data}
$("guestFile")?.addEventListener("change",event=>{currentFile=event.target.files[0]||null;$("guestFileName").textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(2)} Mo`:"";$("toOptions").disabled=!currentFile});
$("toOptions")?.addEventListener("click",()=>show("stepOptions"));$("toContact")?.addEventListener("click",()=>show("stepContact"));document.querySelectorAll(".back").forEach(button=>button.addEventListener("click",()=>show(button.dataset.back)));
$("sendGuestOrder")?.addEventListener("click",async()=>{const phone=$("guestPhone").value.trim(),button=$("sendGuestOrder");if(!currentFile){alert("Choisissez un fichier.");return}if(phone.length<5){$("guestPhone").focus();return}button.disabled=true;button.textContent="Envoi en cours…";try{const body=new FormData();body.append("file",currentFile);body.append("phone",phone);body.append("display_name",$("guestName").value.trim());body.append("copies",$("guestCopies").value);body.append("paper_size",$("guestPaper").value);body.append("color_mode",document.querySelector('input[name="color"]:checked').value);body.append("duplex",$("guestDuplex").checked);const order=await request("/api/v1/public/orders",{method:"POST",body});$("guestPrice").textContent=formatMoney(order.estimated_cost);$("orderNumber").textContent=order.order_number;$("orderStatus").textContent=`Statut : ${order.status} · Paiement : ${order.payment_status} · Estimation : ${formatMoney(order.estimated_cost)}`;const url=new URL(order.tracking_url,location.origin).href;$("trackingLink").textContent=url;$("copyTracking").onclick=()=>navigator.clipboard?.writeText(url);show("stepDone")}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent="Envoyer ma commande"}});
async function loadTracking(){const match=location.pathname.match(/^\/suivi\/([^/]+)\/([^/]+)$/);if(!match)return;$("orderApp").classList.add("hidden");$("trackingApp").classList.remove("hidden");try{const order=await request(`/api/v1/public/orders/${encodeURIComponent(match[1])}/${encodeURIComponent(match[2])}`);$("trackingResult").innerHTML=`<span class="eyebrow">${order.status}</span><h2>${order.order_number}</h2><p>${order.document_name}</p><p>Prix estimé : <b>${formatMoney(order.estimated_cost)}</b></p><p>Paiement : <b>${order.payment_status}</b></p>`}catch(error){$("trackingResult").textContent=error.message}}
loadTracking();
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
