const shop$=id=>document.getElementById(id),money=value=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" FCFA";
let shopProducts=[],shopCart=[],shopPage=0,shopHasMore=true,shopLoading=false,shopObserver=null,shopSearchTimer=null,shopCategoriesLoaded=false;
const shopEsc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function shopRequest(path,options={}){const res=await fetch(path,options);let data={};try{data=await res.json()}catch{}if(!res.ok)throw Error(data.detail||"Une erreur est survenue.");return data}
function saveCart(){localStorage.setItem("fusaa-shop-cart",JSON.stringify(shopCart));renderCart()}
function productCard(product){return `<article class="product"><div class="image">${product.image_url?`<img src="${shopEsc(product.image_url)}" alt="${shopEsc(product.name)}" loading="lazy">`:"Image bientôt disponible"}</div><div class="info"><span class="tag">${shopEsc(product.category?.name||"FUSAA")}</span><h2>${shopEsc(product.name)}</h2><div class="price">${money(product.price_xof)}${product.original_price_xof?`<span class="old">${money(product.original_price_xof)}</span>`:""}</div><p class="stock">${product.stock_quantity>0?`${product.stock_quantity} disponible(s)`:"Rupture de stock"}</p><button ${product.stock_quantity<1?"disabled":""} onclick="addToCart('${product.id}')">Ajouter au panier</button></div></article>`}
function renderProducts({reset=false}={}){const grid=shop$("products");if(reset)grid.innerHTML="";grid.querySelector(".shop-more")?.remove();if(!shopProducts.length&&!shopLoading){grid.innerHTML='<p class="empty">Aucun produit ne correspond à votre recherche.</p>';return}if(shopProducts.length)grid.innerHTML=shopProducts.map(productCard).join("");if(shopHasMore){const more=document.createElement("div");more.className="shop-more";more.textContent=shopLoading?"Chargement des produits…":"Faites défiler pour voir plus de produits";grid.append(more);watchNextPage(more)}}
function watchNextPage(marker){shopObserver?.disconnect();if(!shopHasMore)return;shopObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))loadShop({reset:false})},{rootMargin:"500px 0px"});shopObserver.observe(marker)}
function addToCart(id){const product=shopProducts.find(item=>item.id===id),line=shopCart.find(item=>item.id===id);if(!product)return;if(line){if(line.quantity<product.stock_quantity)line.quantity++}else shopCart.push({id,quantity:1});saveCart()}
function changeCartQuantity(id,change){const product=shopProducts.find(item=>item.id===id),line=shopCart.find(item=>item.id===id);if(!product||!line)return;line.quantity=Math.max(0,Math.min(product.stock_quantity,line.quantity+change));shopCart=shopCart.filter(item=>item.quantity>0);saveCart()}
function renderCart(){shop$("cartCount").textContent=shopCart.reduce((sum,item)=>sum+item.quantity,0);const lines=shopCart.map(line=>({line,product:shopProducts.find(product=>product.id===line.id)})).filter(item=>item.product);const total=lines.reduce((sum,{line,product})=>sum+line.quantity*product.price_xof,0);shop$("cartLines").innerHTML=lines.length?lines.map(({line,product})=>`<div class="line"><span>${shopEsc(product.name)}</span><span class="cart-quantity"><button type="button" class="cart" onclick="changeCartQuantity('${product.id}',-1)">−</button><b>${line.quantity}</b><button type="button" class="cart" onclick="changeCartQuantity('${product.id}',1)" ${line.quantity>=product.stock_quantity?"disabled":""}>+</button></span><span>${money(product.price_xof*line.quantity)} <button type="button" class="cart" onclick="removeCart('${product.id}')">×</button></span></div>`).join(""):'<p class="muted">Votre panier est vide.</p>';shop$("cartTotal").textContent=lines.length?`Total : ${money(total)}`:"";shop$("orderButton").disabled=!lines.length}
function removeCart(id){shopCart=shopCart.filter(line=>line.id!==id);saveCart()}
async function loadShop({reset=true}={}){if(shopLoading||(!reset&&!shopHasMore))return;shopLoading=true;if(reset){shopObserver?.disconnect();shopPage=0;shopHasMore=true;shopProducts=[];shop$("products").innerHTML='<p class="empty">Chargement des produits…</p>'}else renderProducts();try{const params=new URLSearchParams({page:String(shopPage+1),page_size:"12"}),term=shop$("search").value.trim(),category=shop$("category").value;if(term)params.set("q",term);if(category)params.set("category",category);const categoryRequest=shopCategoriesLoaded?Promise.resolve(null):shopRequest("/api/v1/shop/public/categories");const [data,categories]=await Promise.all([shopRequest(`/api/v1/shop/public/products/page?${params}`),categoryRequest]);if(categories){shop$("category").innerHTML='<option value="">Toutes les catégories</option>'+categories.map(item=>`<option value="${shopEsc(item.slug)}">${shopEsc(item.name)}</option>`).join("");shopCategoriesLoaded=true}shopPage=data.page;shopHasMore=data.has_more;shopProducts.push(...data.items);renderProducts({reset:true});renderCart()}catch(error){shop$("products").innerHTML=`<p class="empty">${shopEsc(error.message)}</p>`;shopHasMore=false}finally{shopLoading=false;const marker=document.querySelector(".shop-more");if(marker){marker.textContent=shopHasMore?"Faites défiler pour voir plus de produits":"";if(!shopHasMore)marker.remove();else watchNextPage(marker)}}}
shop$("search").oninput=()=>{clearTimeout(shopSearchTimer);shopSearchTimer=setTimeout(()=>loadShop({reset:true}),280)};shop$("category").onchange=()=>loadShop({reset:true});shop$("cartButton").onclick=()=>{renderCart();shop$("cartDialog").showModal()};shop$("checkout").onsubmit=async event=>{event.preventDefault();const button=shop$("orderButton");button.disabled=true;button.textContent="Envoi…";try{const data=await shopRequest("/api/v1/shop/public/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name:shop$("customerName").value.trim(),customer_phone:shop$("customerPhone").value.trim(),delivery_address:shop$("address").value.trim()||null,payment_method:shop$("payment").value,items:shopCart.map(item=>({product_id:item.id,quantity:item.quantity}))})});shopCart=[];saveCart();shop$("cartDialog").close();shop$("successTitle").textContent=data.order_number;shop$("successText").textContent=`Commande enregistrée : ${money(data.total_xof)}. FUSAA vous contactera au ${data.customer_phone} pour confirmer.`;shop$("successDialog").showModal();loadShop({reset:true})}catch(error){alert(error.message)}finally{button.textContent="Envoyer la commande";button.disabled=false}};
try{shopCart=JSON.parse(localStorage.getItem("fusaa-shop-cart")||"[]")}catch{}loadShop();
