const shop$=id=>document.getElementById(id),money=value=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" FCFA";
let shopProducts=[],shopCart=[],shopPage=0,shopHasMore=true,shopLoading=false,shopObserver=null,shopSearchTimer=null,shopCategoriesLoaded=false;
const shopEsc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let shopOperationDepth=0;function showShopOperation(label="Traitement de votre commande…"){let panel=shop$("shopOperation");if(!panel){document.body.insertAdjacentHTML("beforeend",'<div id="shopOperation" class="shop-operation" role="status" aria-live="polite"><div><i></i><b id="shopOperationLabel"></b><span>FUSAA traite votre demande</span><em><u></u></em></div></div>');panel=shop$("shopOperation")}shopOperationDepth++;shop$("shopOperationLabel").textContent=label;panel.classList.add("active");return performance.now()}async function hideShopOperation(start){const remaining=Math.max(0,700-(performance.now()-start));if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));shopOperationDepth=Math.max(0,shopOperationDepth-1);if(!shopOperationDepth)shop$("shopOperation")?.classList.remove("active")}
async function shopRequest(path,options={}){const animated=String(options.method||"GET").toUpperCase()!=="GET",started=animated?showShopOperation(options.method==="POST"?"Enregistrement de votre commande…":"Mise à jour en cours…"):0;try{const res=await fetch(path,options);let data={};try{data=await res.json()}catch{}if(!res.ok)throw Error(data.detail||"Une erreur est survenue.");return data}finally{if(animated)await hideShopOperation(started)}}
function saveCart(){localStorage.setItem("fusaa-shop-cart",JSON.stringify(shopCart));renderCart()}
function productCard(product){return `<article class="product"><div class="image">${product.image_url?`<img src="${shopEsc(product.image_url)}" alt="${shopEsc(product.name)}" loading="lazy">`:"Image bientôt disponible"}</div><div class="info"><span class="tag">${shopEsc(product.category?.name||"FUSAA")}</span><h2>${shopEsc(product.name)}</h2><div class="price">${money(product.price_xof)}${product.original_price_xof?`<span class="old">${money(product.original_price_xof)}</span>`:""}</div><p class="stock">${product.stock_quantity>0?`${product.stock_quantity} disponible(s)`:"Rupture de stock"}</p><button ${product.stock_quantity<1?"disabled":""} onclick="addToCart('${product.id}')">Ajouter au panier</button></div></article>`}
function renderProducts({reset=false}={}){const grid=shop$("products");if(reset)grid.innerHTML="";grid.querySelector(".shop-more")?.remove();if(!shopProducts.length&&!shopLoading){grid.innerHTML='<p class="empty">Aucun produit ne correspond à votre recherche.</p>';return}if(shopProducts.length)grid.innerHTML=shopProducts.map(productCard).join("");if(shopHasMore){const more=document.createElement("div");more.className="shop-more";more.textContent=shopLoading?"Chargement des produits…":"Faites défiler pour voir plus de produits";grid.append(more);watchNextPage(more)}}
function watchNextPage(marker){shopObserver?.disconnect();if(!shopHasMore)return;shopObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))loadShop({reset:false})},{rootMargin:"500px 0px"});shopObserver.observe(marker)}
function addToCart(id){const product=shopProducts.find(item=>item.id===id),line=shopCart.find(item=>item.id===id);if(!product)return;if(line){if(line.quantity<product.stock_quantity)line.quantity++}else shopCart.push({id,quantity:1});saveCart()}
function changeCartQuantity(id,change){const product=shopProducts.find(item=>item.id===id),line=shopCart.find(item=>item.id===id);if(!product||!line)return;line.quantity=Math.max(0,Math.min(product.stock_quantity,line.quantity+change));shopCart=shopCart.filter(item=>item.quantity>0);saveCart()}
function renderCart(){shop$("cartCount").textContent=shopCart.reduce((sum,item)=>sum+item.quantity,0);const lines=shopCart.map(line=>({line,product:shopProducts.find(product=>product.id===line.id)})).filter(item=>item.product);const total=lines.reduce((sum,{line,product})=>sum+line.quantity*product.price_xof,0);shop$("cartLines").innerHTML=lines.length?lines.map(({line,product})=>`<div class="line"><span>${shopEsc(product.name)}</span><span class="cart-quantity"><button type="button" class="cart" onclick="changeCartQuantity('${product.id}',-1)">−</button><b>${line.quantity}</b><button type="button" class="cart" onclick="changeCartQuantity('${product.id}',1)" ${line.quantity>=product.stock_quantity?"disabled":""}>+</button></span><span>${money(product.price_xof*line.quantity)} <button type="button" class="cart" onclick="removeCart('${product.id}')">×</button></span></div>`).join(""):'<p class="muted">Votre panier est vide.</p>';shop$("cartTotal").textContent=lines.length?`Total : ${money(total)}`:"";shop$("orderButton").disabled=!lines.length}
function removeCart(id){shopCart=shopCart.filter(line=>line.id!==id);saveCart()}
async function loadShop({reset=true}={}){if(shopLoading||(!reset&&!shopHasMore))return;shopLoading=true;if(reset){shopObserver?.disconnect();shopPage=0;shopHasMore=true;shopProducts=[];shop$("products").innerHTML='<p class="empty">Chargement des produits…</p>'}else renderProducts();try{const params=new URLSearchParams({page:String(shopPage+1),page_size:"12"}),term=shop$("search").value.trim(),category=shop$("category").value;if(term)params.set("q",term);if(category)params.set("category",category);const categoryRequest=shopCategoriesLoaded?Promise.resolve(null):shopRequest("/api/v1/shop/public/categories");const [data,categories]=await Promise.all([shopRequest(`/api/v1/shop/public/products/page?${params}`),categoryRequest]);if(categories){shop$("category").innerHTML='<option value="">Toutes les catégories</option>'+categories.map(item=>`<option value="${shopEsc(item.slug)}">${shopEsc(item.name)}</option>`).join("");shopCategoriesLoaded=true}shopPage=data.page;shopHasMore=data.has_more;shopProducts.push(...data.items);renderProducts({reset:true});renderCart()}catch(error){shop$("products").innerHTML=`<p class="empty">${shopEsc(error.message)}</p>`;shopHasMore=false}finally{shopLoading=false;const marker=document.querySelector(".shop-more");if(marker){marker.textContent=shopHasMore?"Faites défiler pour voir plus de produits":"";if(!shopHasMore)marker.remove();else watchNextPage(marker)}}}
shop$("search").oninput=()=>{clearTimeout(shopSearchTimer);shopSearchTimer=setTimeout(()=>loadShop({reset:true}),280)};shop$("category").onchange=()=>loadShop({reset:true});shop$("cartButton").onclick=()=>{renderCart();shop$("cartDialog").showModal()};shop$("checkout").onsubmit=async event=>{event.preventDefault();const button=shop$("orderButton");button.disabled=true;button.textContent="Envoi…";try{const data=await shopRequest("/api/v1/shop/public/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name:shop$("customerName").value.trim(),customer_phone:shop$("customerPhone").value.trim(),delivery_address:shop$("address").value.trim()||null,payment_method:shop$("payment").value,items:shopCart.map(item=>({product_id:item.id,quantity:item.quantity}))})});shopCart=[];saveCart();shop$("cartDialog").close();shop$("successTitle").textContent=data.order_number;shop$("successText").textContent=`Commande enregistrée : ${money(data.total_xof)}. FUSAA vous contactera au ${data.customer_phone} pour confirmer.`;shop$("successDialog").showModal();loadShop({reset:true})}catch(error){alert(error.message)}finally{button.textContent="Envoyer la commande";button.disabled=false}};
try{shopCart=JSON.parse(localStorage.getItem("fusaa-shop-cart")||"[]")}catch{}loadShop();

const SHOP_PAYMENT_TEXT="Paiement via MYNITA, AMANATA ou WAVE : +227 98313369. Discussion WhatsApp : +227 90531465.";
document.head.insertAdjacentHTML("beforeend",'<style>.shop-ai-open{position:fixed;right:20px;bottom:20px;z-index:30;width:auto;margin:0;padding:12px 16px;border-radius:999px;box-shadow:0 14px 35px #0b7df066}.shop-ai{width:min(620px,calc(100vw - 24px));padding:22px;border:1px solid #4be5cf88;border-radius:24px;color:#eaf5ff;background:linear-gradient(145deg,#123148f7,#071522f7);box-shadow:0 28px 90px #000a}.shop-ai::backdrop{background:#03101a88;backdrop-filter:blur(8px)}.shop-ai h2{margin:4px 0}.shop-ai-close{float:right;width:auto;margin:0;padding:6px 10px;background:#ffffff12}.shop-ai-answer{margin:13px 0;padding:13px;border:1px solid #ffffff15;border-radius:13px;background:#061826;color:#cfe0ec;line-height:1.55}.shop-ai-chips{display:flex;gap:7px;flex-wrap:wrap}.shop-ai-chips button{width:auto;margin:0;padding:8px 10px;background:#ffffff10;font-size:.78rem}.payment-guide{margin:14px 0;padding:11px 12px;border:1px solid #35d7bf55;border-radius:12px;background:#0c2a31;color:#d9fff7;font-size:.82rem;line-height:1.55}@media(max-width:520px){.shop-ai-open{right:13px;bottom:13px}.shop-ai{padding:17px}}</style>');
document.querySelector("#checkout .notice")?.insertAdjacentHTML("afterend",'<p class="payment-guide">'+SHOP_PAYMENT_TEXT+'</p>');
const paymentSelect=shop$("payment");if(paymentSelect)paymentSelect.innerHTML='<option value="À confirmer">À confirmer avec FUSAA</option><option value="MYNITA">MYNITA · +227 98313369</option><option value="AMANATA">AMANATA · +227 98313369</option><option value="WAVE">WAVE · +227 98313369</option>';
const previousCheckout=shop$("checkout").onsubmit;shop$("checkout").onsubmit=async event=>{await previousCheckout(event);const success=shop$("successDialog");if(success.open&&!shop$("shopPaymentConfirmation"))shop$("successText").insertAdjacentHTML("afterend",'<p id="shopPaymentConfirmation" class="payment-guide">'+SHOP_PAYMENT_TEXT+'</p>')};
document.body.insertAdjacentHTML("beforeend",'<button id="shopAiOpen" class="shop-ai-open" type="button">✦ Assistant FUSAA</button><dialog id="shopAiDialog" class="shop-ai"><button id="shopAiClose" class="shop-ai-close" type="button">×</button><span class="eyebrow">ASSISTANT BOUTIQUE</span><h2 id="shopAiTitle">Comment puis-je vous aider ?</h2><p class="muted">Questions sur les produits, le panier, la livraison et le paiement.</p><div id="shopAiChips" class="shop-ai-chips"></div><label class="field" for="shopAiQuestion">VOTRE QUESTION<input id="shopAiQuestion" placeholder="Ex. Comment payer ma commande ?"></label><button id="shopAiAsk" type="button">Demander</button><div id="shopAiAnswer" class="shop-ai-answer">Bonjour ! Je peux vous aider à faire un achat ou à payer.</div></dialog>');
const shopAiPrompts=["Bonjour","Comment payer ?","Voir mon panier","Discuter sur WhatsApp"];
function renderShopAiChips(items=shopAiPrompts){const target=shop$("shopAiChips");target.replaceChildren(...items.map(item=>{const button=document.createElement("button");button.type="button";button.textContent=item;button.onclick=()=>askShopAssistant(item);return button}))}
async function askShopAssistant(prompt=null){const input=shop$("shopAiQuestion"),answer=shop$("shopAiAnswer"),button=shop$("shopAiAsk"),message=(prompt||input.value).trim();if(!message){input.focus();return}if(/panier/i.test(message))shop$("cartButton").click();input.value="";button.disabled=true;button.textContent="Réponse…";answer.textContent="Analyse de votre demande…";try{const data=await shopRequest("/api/v1/public/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,profile:"shop_guest"})});shop$("shopAiTitle").textContent=data.title;answer.textContent=data.answer;renderShopAiChips(data.suggestions||shopAiPrompts)}catch(error){answer.textContent=error.message}finally{button.disabled=false;button.textContent="Demander"}}
shop$("shopAiOpen").onclick=()=>{if(!shop$("shopAiDialog").open)shop$("shopAiDialog").showModal();renderShopAiChips()};shop$("shopAiClose").onclick=()=>shop$("shopAiDialog").close();shop$("shopAiAsk").onclick=()=>askShopAssistant();shop$("shopAiQuestion").onkeydown=event=>{if(event.key==="Enter"){event.preventDefault();askShopAssistant()}};
const shopNav=document.getElementById("shopNav");if(shopNav&&!shopNav.querySelector("[data-shop-login]"))shopNav.insertAdjacentHTML("beforeend",'<a href="/admin" data-shop-login="true">Se connecter</a>');
window.addEventListener("storage",event=>{if(event.key!=="fusaa-theme")return;const theme=event.newValue==="light"?"light":"dark";document.documentElement.dataset.theme=theme;const button=document.getElementById("shopTheme");if(button)button.textContent=theme==="light"?"☾ Sombre":"☀ Clair"});
document.head.insertAdjacentHTML("beforeend",'<style>.shop-operation,.public-operation{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:20px;background:#03101a70;backdrop-filter:blur(6px);opacity:0;pointer-events:none;transition:opacity .2s ease}.shop-operation.active,.public-operation.active{opacity:1;pointer-events:auto}.shop-operation>div,.public-operation>div{width:min(360px,100%);padding:28px;border:1px solid #46e1ce88;border-radius:24px;background:linear-gradient(145deg,#123149f7,#071522fa);box-shadow:0 28px 90px #000a;text-align:center}.shop-operation i,.public-operation i{display:block;width:58px;height:58px;margin:0 auto 16px;border:5px solid #ffffff18;border-top-color:#36e1c7;border-right-color:#287cf0;border-radius:50%;animation:shopOperationSpin .8s linear infinite;box-shadow:0 0 30px #26d2b566}.shop-operation b,.public-operation b{display:block;color:#effbff;font-size:1.05rem}.shop-operation span,.public-operation span{display:block;margin:7px 0 16px;color:#a7c3d3;font-size:.82rem}.shop-operation em,.public-operation em{display:block;height:7px;overflow:hidden;border-radius:99px;background:#ffffff14}.shop-operation u,.public-operation u{display:block;width:48%;height:100%;border-radius:inherit;background:linear-gradient(90deg,#25d3b8,#287cf0);animation:shopOperationLoad 1.05s ease-in-out infinite}@keyframes shopOperationSpin{to{transform:rotate(360deg)}}@keyframes shopOperationLoad{50%{transform:translateX(108%)}}:root[data-theme="light"] .shop-operation>div,:root[data-theme="light"] .public-operation>div{background:linear-gradient(145deg,#fff,#eaf6f7)}:root[data-theme="light"] .shop-operation b,:root[data-theme="light"] .public-operation b{color:#183247}:root[data-theme="light"] .shop-operation span,:root[data-theme="light"] .public-operation span{color:#557185}@media(prefers-reduced-motion:reduce){.shop-operation i,.shop-operation u,.public-operation i,.public-operation u{animation:none}}</style>');
document.head.insertAdjacentHTML("beforeend",'<style>button:not(:disabled){transition:transform .2s ease,filter .2s ease,box-shadow .25s ease!important;transform-origin:center}button.fusaa-clicked:not(:disabled){animation:fusaaButtonClick .62s cubic-bezier(.2,.8,.25,1);filter:brightness(1.12);box-shadow:0 0 0 5px #35dfc236,0 0 26px #2d9bf066!important}@keyframes fusaaButtonClick{0%{transform:scale(1)}26%{transform:translateY(2px) scale(.94)}58%{transform:translateY(-1px) scale(1.025)}100%{transform:scale(1)}}@media(prefers-reduced-motion:reduce){button.fusaa-clicked:not(:disabled){animation:none}}</style>');
function animateShopButton(button){if(!button||button.disabled)return;button.classList.remove("fusaa-clicked");void button.offsetWidth;button.classList.add("fusaa-clicked");setTimeout(()=>button.classList.remove("fusaa-clicked"),650)}document.addEventListener("click",event=>animateShopButton(event.target.closest("button")),true);document.addEventListener("submit",event=>animateShopButton(event.target.querySelector('button[type="submit"],button')),true);
