const shop$=id=>document.getElementById(id),money=value=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(value||0)+" FCFA";
let shopProducts=[],shopCart=[];
const shopEsc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function shopRequest(path,options={}){const res=await fetch(path,options);let data={};try{data=await res.json()}catch{}if(!res.ok)throw Error(data.detail||"Une erreur est survenue.");return data}
function saveCart(){localStorage.setItem("fusaa-shop-cart",JSON.stringify(shopCart));renderCart()}
function renderProducts(){const term=shop$("search").value.toLowerCase(),category=shop$("category").value;const items=shopProducts.filter(p=>(!category||p.category?.slug===category)&&(!term||[p.name,p.brand,p.description].join(" ").toLowerCase().includes(term)));shop$("products").innerHTML=items.length?items.map(p=>`<article class="product"><div class="image">${p.image_url?`<img src="${shopEsc(p.image_url)}" alt="${shopEsc(p.name)}">`:"Image bientôt disponible"}</div><div class="info"><span class="tag">${shopEsc(p.category?.name||"FUSAA")}</span><h2>${shopEsc(p.name)}</h2><div class="price">${money(p.price_xof)}${p.original_price_xof?`<span class="old">${money(p.original_price_xof)}</span>`:""}</div><p class="stock">${p.stock_quantity>0?`${p.stock_quantity} disponible(s)`:"Rupture de stock"}</p><button ${p.stock_quantity<1?"disabled":""} onclick="addToCart('${p.id}')">Ajouter au panier</button></div></article>`).join(""):'<p class="empty">Aucun produit ne correspond à votre recherche.</p>'}
function addToCart(id){const product=shopProducts.find(p=>p.id===id),line=shopCart.find(x=>x.id===id);if(!product)return;if(line){if(line.quantity<product.stock_quantity)line.quantity++}else shopCart.push({id,quantity:1});saveCart()}
function renderCart(){shop$("cartCount").textContent=shopCart.reduce((sum,x)=>sum+x.quantity,0);const lines=shopCart.map(line=>({line,product:shopProducts.find(p=>p.id===line.id)})).filter(x=>x.product);const total=lines.reduce((sum,{line,product})=>sum+line.quantity*product.price_xof,0);shop$("cartLines").innerHTML=lines.length?lines.map(({line,product})=>`<div class="line"><span>${shopEsc(product.name)} × ${line.quantity}</span><span>${money(product.price_xof*line.quantity)} <button class="cart" onclick="removeCart('${product.id}')">×</button></span></div>`).join(""):'<p class="muted">Votre panier est vide.</p>';shop$("cartTotal").textContent=lines.length?`Total : ${money(total)}`:"";shop$("orderButton").disabled=!lines.length}
function removeCart(id){shopCart=shopCart.filter(line=>line.id!==id);saveCart()}
async function loadShop(){const [products,categories]=await Promise.all([shopRequest("/api/v1/shop/public/products"),shopRequest("/api/v1/shop/public/categories")]);shopProducts=products;shop$("category").innerHTML='<option value="">Toutes les catégories</option>'+categories.map(c=>`<option value="${shopEsc(c.slug)}">${shopEsc(c.name)}</option>`).join("");renderProducts();renderCart()}
shop$("search").oninput=renderProducts;shop$("category").onchange=renderProducts;shop$("cartButton").onclick=()=>{renderCart();shop$("cartDialog").showModal()};shop$("checkout").onsubmit=async event=>{event.preventDefault();const button=shop$("orderButton");button.disabled=true;button.textContent="Envoi…";try{const data=await shopRequest("/api/v1/shop/public/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name:shop$("customerName").value.trim(),customer_phone:shop$("customerPhone").value.trim(),delivery_address:shop$("address").value.trim()||null,payment_method:shop$("payment").value,items:shopCart.map(x=>({product_id:x.id,quantity:x.quantity}))})});shopCart=[];saveCart();shop$("cartDialog").close();shop$("successTitle").textContent=data.order_number;shop$("successText").textContent=`Commande enregistrée : ${money(data.total_xof)}. FUSAA vous contactera au ${data.customer_phone} pour confirmer.`;shop$("successDialog").showModal();await loadShop()}catch(error){alert(error.message)}finally{button.textContent="Envoyer la commande";button.disabled=false}};
try{shopCart=JSON.parse(localStorage.getItem("fusaa-shop-cart")||"[]")}catch{}loadShop().catch(error=>shop$("products").innerHTML=`<p class="empty">${shopEsc(error.message)}</p>`);
