"""Print Core foundation.

Revision ID: 0001_print_core
Revises:
Create Date: 2026-09-04
"""
from alembic import op
import sqlalchemy as sa
revision="0001_print_core"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("email",sa.String(320),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("display_name",sa.String(120),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)));op.create_index("ix_users_email","users",["email"],unique=True)
    op.create_table("organizations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)));op.create_index("ix_organizations_name","organizations",["name"],unique=True)
    op.create_table("workshops",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)))
    op.create_table("computer_agents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("workshop_id",sa.String(36),sa.ForeignKey("workshops.id"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("enrollment_token",sa.String(128),nullable=False),sa.Column("agent_key",sa.String(128)),sa.Column("machine_fingerprint",sa.String(255)),sa.Column("last_heartbeat_at",sa.DateTime(timezone=True)),sa.Column("is_online",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)));op.create_index("ix_computer_agents_enrollment_token","computer_agents",["enrollment_token"],unique=True)
    op.create_table("printers",sa.Column("id",sa.String(36),primary_key=True),sa.Column("computer_agent_id",sa.String(36),sa.ForeignKey("computer_agents.id"),nullable=False),sa.Column("system_name",sa.String(255),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("manufacturer",sa.String(120)),sa.Column("model",sa.String(120)),sa.Column("status",sa.String(32),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("color_supported",sa.Boolean(),nullable=False),sa.Column("duplex_supported",sa.Boolean(),nullable=False),sa.Column("capabilities",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("computer_agent_id","system_name",name="uq_printer_system"))
    op.create_table("documents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("original_name",sa.String(255),nullable=False),sa.Column("storage_key",sa.String(512),nullable=False),sa.Column("mime_type",sa.String(100),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("preview_key",sa.String(512)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("storage_key"))
    job_status=sa.Enum("RECEIVED","ANALYZING","WAITING_APPROVAL","READY","QUEUED","PRINTING","COMPLETED","FAILED","CANCELLED","IGNORED",name="jobstatus")
    op.create_table("print_jobs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("workshop_id",sa.String(36),sa.ForeignKey("workshops.id"),nullable=False),sa.Column("computer_agent_id",sa.String(36),sa.ForeignKey("computer_agents.id")),sa.Column("printer_id",sa.String(36),sa.ForeignKey("printers.id")),sa.Column("document_id",sa.String(36),sa.ForeignKey("documents.id"),nullable=False),sa.Column("source",sa.String(40),nullable=False),sa.Column("status",job_status,nullable=False),sa.Column("copies",sa.Integer(),nullable=False),sa.Column("paper_size",sa.String(30)),sa.Column("orientation",sa.String(20)),sa.Column("color_mode",sa.String(20)),sa.Column("duplex",sa.Boolean(),nullable=False),sa.Column("pages",sa.String(120)),sa.Column("instructions",sa.Text()),sa.Column("idempotency_key",sa.String(128)),sa.Column("error_message",sa.Text()),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)));op.create_index("ix_print_jobs_idempotency_key","print_jobs",["idempotency_key"],unique=True)
    command_status=sa.Enum("PENDING","CLAIMED","SUCCESS","FAILED","CANCELLED",name="commandstatus")
    op.create_table("agent_commands",sa.Column("id",sa.String(36),primary_key=True),sa.Column("computer_agent_id",sa.String(36),sa.ForeignKey("computer_agents.id"),nullable=False),sa.Column("print_job_id",sa.String(36),sa.ForeignKey("print_jobs.id"),nullable=False),sa.Column("command_type",sa.String(40),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("status",command_status,nullable=False),sa.Column("result",sa.JSON()),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("idempotency_key"))
    op.create_table("audit_logs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(80),nullable=False),sa.Column("resource_type",sa.String(80),nullable=False),sa.Column("resource_id",sa.String(36),nullable=False),sa.Column("parameters",sa.JSON(),nullable=False),sa.Column("result",sa.String(40),nullable=False),sa.Column("ip",sa.String(64)),sa.Column("agent_id",sa.String(36)),sa.Column("timestamp",sa.DateTime(timezone=True)))
def downgrade():
    for table in ["audit_logs","agent_commands","print_jobs","documents","printers","computer_agents","workshops","organizations","users"]:op.drop_table(table)
